title: "Galen's PCT Tracker"
description: "Map, progress, photos & short updates from the trail"
url: ""  # GitHub Pages sets this
baseurl: "/hike-tracker"  # set to "/REPO_NAME" if needed
markdown: kramdown
theme: null
permalink: pretty
